version: "3.8"

services:
  website:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - ./website:/usr/local/apache2/htdocs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
